### ISSUE TITLE
Unify TicTacToe's logics

### ISSUE THREAD

**Issue by Qwebeck** [aI-lab-glider/ai-course-games-tree-search#27]
Currently two versions of the game exists:

- tic tac toe
- ultimate tic tac toe

Both have similar logic (e.g checking for a winner sigh or drawing an image) and as such could be unified.

Actually not sure if it is needed, as it will make a codebase a little bit harder for understanding (at least if we will do with an inheritance).

**Comment by mslazynski** [comment]
Removing code duplication just for the sake of it is not a good idea. Following blindly the DRY principle just increases the code coupling and is considered harmful.  

- https://www.entropywins.wtf/blog/2017/09/06/the-fallacy-of-dry/
- https://rotemtam.com/2020/05/18/the-dry-principle-is-bad-advice/
- https://medium.com/@nicolopigna/this-is-not-the-dry-you-are-looking-for-a316ed3f445f

**Comment by Qwebeck** [comment]
Closed by PR: https://github.com/aI-lab-glider/ai-course-games-tree-search/pull/29
